name: Build mkdocs

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install package
        run: |
          pip install git+git://github.com/airctic/icevision.git#egg=icevision[all] --upgrade
          pip install -e ".[dev]"

      - name: Build the docs
        run:  |
          cd docs
          python autogen.py
          mkdocs build

      - name: Deploy docs (if pushing to master)
        if: github.repository == 'airctic/icedata' && github.event_name == 'push'
        run: cd docs && mkdocs gh-deploy --force
